# Generated by Django 3.1.6 on 2021-02-08 03:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_auto_20210205_0034'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='title',
        ),
        migrations.RemoveField(
            model_name='user',
            name='followed_users',
        ),
        migrations.AddField(
            model_name='card',
            name='alignment',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='color',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='font',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='image',
            field=models.ImageField(null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='card',
            name='size',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='style',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='card',
            name='weight',
            field=models.CharField(default='', max_length=100, null=True),
        ),
        migrations.CreateModel(
            name='UserFollowing',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('following_user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='followers', to=settings.AUTH_USER_MODEL)),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='following', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created'],
            },
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(fields=('user_id', 'following_user_id'), name='unique_followers'),
        ),
    ]
