# Generated by Django 3.1.6 on 2021-02-08 04:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_auto_20210208_0337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='size',
            field=models.IntegerField( null=True),
        ),
    ]
