# Generated by Django 3.1.6 on 2021-02-08 05:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_auto_20210208_0510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='size',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
