# Generated by Django 3.1.6 on 2021-02-08 05:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210208_0511'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='textbox_alignment',
            field=models.CharField(default='', max_length=100, null=True),
        ),
    ]
