# Generated by Django 3.1.6 on 2021-02-08 05:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_card_textbox_alignment'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='textbox_alignment',
            new_name='textboxalignment',
        ),
    ]
