# Generated by Django 3.1.6 on 2021-02-08 18:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210208_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='size',
            field=models.CharField(default='gi', max_length=100, null=True),
        ),
    ]
