# Generated by Django 3.1.6 on 2021-02-09 04:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210209_0251'),
    ]

    operations = [
        migrations.RenameField(
            model_name='card',
            old_name='Access',
            new_name='access',
        ),
    ]
