# Generated by Django 3.1.6 on 2021-02-09 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_auto_20210209_1732'),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name='userfollowing',
            name='unique_followers',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='user',
            new_name='fromuser',
        ),
        migrations.RenameField(
            model_name='userfollowing',
            old_name='following_user',
            new_name='touser',
        ),
        migrations.AddConstraint(
            model_name='userfollowing',
            constraint=models.UniqueConstraint(fields=('fromuser', 'touser'), name='unique_followers'),
        ),
    ]
