# Generated by Django 3.1.6 on 2021-02-09 21:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0022_auto_20210209_1920'),
    ]

    operations = [
        migrations.AlterField(
            model_name='card',
            name='image',
            field=models.URLField(blank=True, null=True),
        ),
    ]
